### ISSUE TITLE
Failed Windows and linux builds

### ISSUE THREAD

**Issue by djhoese** [conda-forge/trollimage-feedstock#1]
![image](https://user-images.githubusercontent.com/1828519/42338516-ad4520ec-804f-11e8-907c-242c5d83c11b.png)

There were failed builds for Windows for python 2.7 and 3.6: https://ci.appveyor.com/project/conda-forge/trollimage-feedstock/branch/master

And on linux for python 3.5: https://circleci.com/gh/conda-forge/trollimage-feedstock: https://circleci.com/gh/conda-forge/trollimage-feedstock/1

I don't seem to have permission to restart these jobs. Do I need to make a PR?

**Comment by djhoese** [comment]
I think this is the cause for this issue: https://github.com/conda-forge/satpy-feedstock/issues/1

**Comment by ocefpaf** [comment]
> There were failed builds for Windows for python 2.7 and 3.6: ci.appveyor.com/project/conda-forge/trollimage-feedstock/branch/master

I don't see failed builds, just a job queue. All the maintainers will get access to the CIs to restart them, but if this is a new feedstock it may take a while.

**Comment by djhoese** [comment]
@ocefpaf I realized on appveyor I was logged in to the wrong user account and circle-ci I wasn't logged in at all. I restarted appveyor, about to restart circle-ci. Thanks. I'll close this when builds pass.

**Comment by djhoese** [comment]
All builds seemed to have passed. Packages show up on anaconda.org.
