### ISSUE TITLE
Remove broken trollimage 1.6.1

### ISSUE THREAD

**Issue by djhoese** [conda-forge/trollimage-feedstock#8]
I messed up the tests for trollimage's 1.6.1 and missed a very important use case with the changes I made. Therefore version 1.6.1 is considered completely broken and should not be used by any user. I am working on a 1.6.2 fix now.

@ocefpaf Can you remove this version of the package? Is it possible for me to be able to do this in the future on anaconda.org? Who should I tag if this needs to be done in the future?

**Comment by ocefpaf** [comment]
> @ocefpaf Can you remove this version of the package?

Done. See https://anaconda.org/conda-forge/trollimage/files?version=1.6.1

> Is it possible for me to be able to do this in the future on anaconda.org?

That is one of the few things only core members can do b/c we don't have the right permission granularity to allow users to remove only their package.

> Who should I tag if this needs to be done in the future?

@conda-forge/core +some people who you will know respond is fine.
Urgent matters can also be reported on gitter.

**Comment by djhoese** [comment]
Thanks!
